// newfrontend/src/App.vue
<template>
  <z-canvas :views='viewMap'></z-canvas>
</template>
<script>
export default {
  data () {
    return {
      viewMap: {
        holon: 'holon',
        tasks: 'tasks',
        holons: 'holons',
        users: 'users',
        projects: 'projects',
        settings: 'settings'
      }
    }
  },
  mounted () {
    this.$zircle.config({
      usePercentSizes: true,
      mode: 'full',
      style: {
        theme: 'black',
        mode: 'dark'
      },
      debug: false
    })

    var holonId = this.$route.params.holonId || ''
    var lense = this.$route.params.lense || null

    if (holonId && lense) {
      // URL like /regenerativa/quests → navigate to holon with dotted id
      this.$zircle.toView({
        to: 'holon',
        fromSpot: { position: { Xabs: 0, Yabs: 0, scale: 1 } },
        params: { id: holonId + '.' + lense }
      })
    } else if (holonId) {
      // URL like /regenerativa → navigate to that holon
      this.$zircle.toView({
        to: 'holon',
        fromSpot: { position: { Xabs: 0, Yabs: 0, scale: 1 } },
        params: { id: holonId }
      })
    } else {
      // Root URL → show home
      this.$zircle.toView('holon')
    }
  }
}
</script>
<style>
a {
  color: var(--primary);
  font-style: bold
}
@import url('https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,700');
@import url('https://use.fontawesome.com/releases/v5.1.0/css/all.css');
</style>

// svelte-frontend/src/App.svelte
<script>
  import { onMount } from 'svelte';
  import { ZCanvas, zircle } from './lib/zircle/index.js';
  import './lib/zircle/zircle.css';

  // Import all views
  import Holon from './views/Holon.svelte';
  import Holons from './views/Holons.svelte';
  import Tasks from './views/Tasks.svelte';
  import Users from './views/Users.svelte';
  import Projects from './views/Projects.svelte';
  import Settings from './views/Settings.svelte';

  // Views object for ZCanvas
  const views = {
    holon: Holon,
    holons: Holons,
    tasks: Tasks,
    users: Users,
    projects: Projects,
    settings: Settings
  };

  onMount(() => {
    // Configure zircle
    zircle.config({
      usePercentSizes: true,
      mode: 'full',
      style: {
        theme: 'black',
        mode: 'dark'
      },
      debug: false
    });

    // Navigate to initial view
    zircle.toView('holon');
  });
</script>

<ZCanvas {views} />

<style>
  :global(body) {
    margin: 0;
    padding: 0;
    overflow: hidden;
    font-family: 'Source Sans Pro', sans-serif;
  }

  :global(a) {
    color: var(--z-primary);
    font-weight: bold;
  }
</style>
