// newfrontend/App.vue
<template>
  <z-canvas :views='$options.components'></z-canvas>
</template>
<script>
// TO SET UP VUE-ROUTER UNCOMMENT THE FOLLOWING LINES
import Vue from 'vue'
import Router from 'vue-router'
Vue.use(Router)
const router = new Router()
export default {
  components: {
    holon: () => import('./views/holon'),
    settings: () => import('./views/settings')
  },
  mounted () {
    this.$zircle.config({
      router: router,
      mode: 'full',
      style: {
        theme: 'black',
        mode: 'dark'
      },
      debug: true
    })
    this.$zircle.setView('holon')
  }
}
</script>
<style>
@import url('https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,700');
@import url('https://use.fontawesome.com/releases/v5.1.0/css/all.css');
</style>

// svelte-frontend/src/App.svelte
<script>
  import { onMount } from 'svelte';
  import { ZCanvas, zircle } from './lib/zircle/index.js';
  import './lib/zircle/zircle.css';

  // Import all views
  import Holon from './views/Holon.svelte';
  import Holons from './views/Holons.svelte';
  import Tasks from './views/Tasks.svelte';
  import Users from './views/Users.svelte';
  import Projects from './views/Projects.svelte';
  import Settings from './views/Settings.svelte';

  // Views object for ZCanvas
  const views = {
    holon: Holon,
    holons: Holons,
    tasks: Tasks,
    users: Users,
    projects: Projects,
    settings: Settings
  };

  onMount(() => {
    // Configure zircle
    zircle.config({
      usePercentSizes: true,
      mode: 'full',
      style: {
        theme: 'black',
        mode: 'dark'
      },
      debug: false
    });

    // Navigate to initial view
    zircle.toView('holon');
  });
</script>

<ZCanvas {views} />

<style>
  :global(body) {
    margin: 0;
    padding: 0;
    overflow: hidden;
    font-family: 'Source Sans Pro', sans-serif;
  }

  :global(a) {
    color: var(--z-primary);
    font-weight: bold;
  }
</style>
