// newfrontend/src/views/projects.vue
<template>
  <z-view label="Project">
    Project <br/> {{ id }}
    <div slot="extension">
      <z-spot v-for="(holon, index) in holons" :key="holon.id" :knob="editing ? true : false"
        @click.native= normalize(index)
        :index= index
        :label="holon.label"
        :angle="200 - (index * (220. / (holons.length > 1 ? holons.length - 1 : 1)))" size="m" :distance="130"
        :label-pos="index >= holons.length / 2 ? 'right' : 'left'"
        :to-view=" { name: holon.lense ? holon.lense : 'holon', params: { id: holon.id } }">
        <!-- :style="[{backgroundImage:`url(${holonsimages[index]})`},{backgroundSize: `100% 100%`},{backgroundRepeat: `no-repeat`},{backgroundPosition: `center`},{borderWidth:'$(holonsvalues[index])px'}]"
      -->
       
        <!-- :imagePath = "holonsimages[index]?'./images/'+ holonsimages[index]:''" -->
      </z-spot>
      <!-- <z-spot v-for="(el, index) in this.holons" button size="xs" :distance="120" :label="el.label"
         :key="index" @click.native="" /> -->
    </div>
  </z-view>
</template>
<script>

import HoloSphere from 'holosphere'

let hs = new HoloSphere("Holons")

export default {
  watch: {
    // id: function () {
    //   console.log('called! ' + this.id)
    //   this.fetchInfo()
    // },
    // holons: function () {
    //   console.log('called! ' + this.holons.length)
    // },
    // holons: function () {
    //   console.log('called! ' + this.holons.length)
    // },
    deep: true,

    $route(to, from) {
      console.log(to)
      console.log(from)
    }
  },
  data() {
    return {
      id: '',
      name: '',
      lense: 'holons',
      description: "Holon",
      holons: []
    }
  },
  async mounted() {
    await this.fetchInfo()
  },
  methods: {
   
    async fetchInfo() {
      if (this.$zircle.getParams()) {
        this.id = this.$zircle.getParams().id
        this.lense = this.$zircle.getParams().lense
      }
      let id = this.id
      var table = await hs.get(this.id, 'quests') // TODO: load github/npm project info
      var tableid = id.split('.')[0]
      var lense = id.split('.')[1]
      var itemid = id.split('.')[2]
      this.holons = [
        { 'id': id , 'label': 'Contributors', 'lense': 'contributors' },
        { 'id': id , 'label': 'Dependencies', 'lense': 'dependencies' },
        { 'id': id , 'label': 'Issues', 'lense': 'issues' }
      ]
      return
    }
  }
}
</script>

// svelte-frontend/src/views/Projects.svelte
<script>
  import { onMount } from 'svelte';
  import { ZView, ZSpot, zircle } from '../lib/zircle/index.js';
  import { getHoloSphere } from '../libs/holons.js';

  // State
  let id = '';
  let name = '';
  let lense = 'holons';
  let description = 'Holon';
  let holons = [];
  let editing = false;

  function getParams() {
    const state = $zircle;
    return state.params || {};
  }

  function calculateAngle(index, total) {
    return 200 - (index * (220 / (total > 1 ? total - 1 : 1)));
  }

  function getLabelPos(index, total) {
    return index >= total / 2 ? 'right' : 'left';
  }

  function normalize(idx) {
    console.log('Normalizing index:', idx);
  }

  async function fetchInfo() {
    const params = getParams();
    if (params.id) {
      id = params.id;
    }
    if (params.lense) {
      lense = params.lense;
    }

    try {
      const hs = await getHoloSphere();
      // TODO: load github/npm project info
      await hs.get(id, 'quests');
    } catch (e) {
      console.warn('HoloSphere fetch error:', e);
    }

    // Set project-related holons
    holons = [
      { 'id': id, 'label': 'Contributors', 'lense': 'contributors' },
      { 'id': id, 'label': 'Dependencies', 'lense': 'dependencies' },
      { 'id': id, 'label': 'Issues', 'lense': 'issues' }
    ];
  }

  onMount(() => {
    fetchInfo();
  });
</script>

<ZView label="Project">
  <div>
    Project <br/> {id}
  </div>

  <div slot="extension">
    {#each holons as holon, index (holon.id + '-' + index)}
      <ZSpot
        knob={editing}
        on:click={() => normalize(index)}
        {index}
        label={holon.label}
        angle={calculateAngle(index, holons.length)}
        size="m"
        distance={130}
        labelPos={getLabelPos(index, holons.length)}
        toView={{ name: holon.lense || 'holon', params: { id: holon.id } }}
      />
    {/each}
  </div>
</ZView>
